### ISSUE TITLE
handleDelete

### ISSUE THREAD

**Issue by r00bal** [MateuszWoj-bit/goit-react-hw-02-phonebook#4]
https://github.com/MateuszWoj-bit/goit-react-hw-02-phonebook/blob/545249d34b3f17b346de3d63dfdb00b521e6a6c1/src/components/App.jsx#L35-L43

Nazwa metody `handleClick`  mało mówi do czego on ma służyć, troche za bardzo ogólna ta nazwa. Nazwy zmiennych i funkcji powinny już w jakiś sposób je opisywać i tłumaczyć co robią. Ten Click ma służyć do kasowania kontaktów więc może np.  `handleDelete` będzie bardziej pasował. 

Do odnalezienia używasz tutaj atrybutu index, który nadałaś na każdym buttonie w `<button index={id} type="button" onClick={() => onClick(id)}>` nie ma takiego atrybuty w htmlu. Tutaj napewno lepiej będzie wykorzystać id które płynie w propsach np.
`<button onClick={() => onClick(id)}>`

Samą funkcje można uprościć do:
```
 handleClick = id => {
    const filteredContacts = this.state.contacts.filter(
      contact => contact.id !== id
    );
    this.setState({ contacts: filteredContacts });
  };
```
`filter` nie mutuje tablicy na której został użyty tylko zwraca nową więc jest ok

**Comment by MateuszWoj-bit** [comment]
Wykonane :)
